# Generated by Django 6.0.2 on 2026-02-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Día de Nacimiento'),
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mes de Nacimiento'),
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de Nacimiento'),
        ),
    ]
