# Generated by Django 6.0.1 on 2026-02-10 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_featureflag_feature_key'),
        ('customers', '0002_remove_customer_birth_date_customer_birth_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la Etiqueta')),
                ('color', models.CharField(default='#6c757d', max_length=20, verbose_name='Color (Hex)')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='customers', to='customers.tag', verbose_name='Etiquetas'),
        ),
    ]
