# Generated by Django 6.0.1 on 2026-02-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_tag_customer_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dni',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='DNI/ID'),
        ),
    ]
