# Generated by Django 6.0.2 on 2026-02-10 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('core', '0006_alter_featureflag_feature_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_api_url', models.URLField(blank=True, help_text='Ej: https://api.ultramsg.com/instance123/messages/chat', max_length=500, verbose_name='WhatsApp API URL')),
                ('whatsapp_token', models.CharField(blank=True, max_length=255, verbose_name='WhatsApp Token')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='Habilitar Emails')),
                ('template_one_left', models.TextField(blank=True, verbose_name='Plantilla: Falta 1 sello')),
                ('template_completed', models.TextField(blank=True, verbose_name='Plantilla: Tarjeta Completada')),
                ('template_expiring', models.TextField(blank=True, verbose_name='Plantilla: Por Vencer (7 días)')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
            },
        ),
    ]
