# Generated by Django 6.0.1 on 2026-02-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_notificationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationconfig',
            name='birthday_enabled',
            field=models.BooleanField(default=False, verbose_name='Habilitar Saludos de Cumpleaños'),
        ),
        migrations.AddField(
            model_name='notificationconfig',
            name='birthday_template',
            field=models.TextField(default='¡Feliz cumpleaños {nombre}! 🎉🎂 De parte de todo el equipo de {negocio} te deseamos lo mejor. ¡Ven hoy y recibe un descuento especial! 🎁', verbose_name='Plantilla: Cumpleaños'),
        ),
    ]
