# Generated by Django 6.0.1 on 2026-02-10 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_notificationconfig_birthday_enabled_and_more'),
        ('core', '0006_alter_featureflag_feature_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Plantilla')),
                ('content', models.TextField(verbose_name='Contenido del Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Plantilla de Campaña',
                'verbose_name_plural': 'Plantillas de Campañas',
            },
        ),
    ]
