# Generated by Django 6.0.2 on 2026-02-09 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_featureflag_usagelimit'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EARN', 'Ganancia'), ('REDEEM', 'Canje'), ('ADJUST', 'Ajuste Manual')], default='EARN', max_length=10, verbose_name='Tipo')),
                ('points', models.IntegerField(verbose_name='Puntos')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='customers.customer', verbose_name='Cliente')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='Organización')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Transacción de Puntos',
                'verbose_name_plural': 'Transacciones de Puntos',
                'ordering': ['-created_at'],
            },
        ),
    ]
