# Generated by Django 6.0.2 on 2026-02-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, unique=True, verbose_name='Dominio')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Es Principal')),
            ],
            options={
                'verbose_name': 'Dominio',
                'verbose_name_plural': 'Dominios',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Negocio')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug URL')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Color Primario')),
                ('timezone', models.CharField(default='America/Lima', max_length=50, verbose_name='Zona Horaria')),
                ('currency', models.CharField(default='PEN', max_length=3, verbose_name='Moneda')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
            },
        ),
    ]
