# Generated by Django 6.0.2 on 2026-02-09 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(choices=[('customers', 'Gestión de Clientes'), ('services', 'Catálogo de Servicios'), ('points', 'Sistema de Puntos'), ('stamps', 'Sistema de Sellos (Punch Cards)'), ('rewards', 'Recompensas'), ('appointments', 'Sistema de Citas'), ('campaigns', 'Campañas de Marketing'), ('reports', 'Reportes Avanzados'), ('subscriptions', 'Suscripciones'), ('integrations', 'Integraciones (Pabbly/Webhooks)'), ('gamification', 'Gamificación'), ('audit', 'Auditoría y Logs'), ('customers.import_csv', 'Importar Clientes CSV'), ('customers.export_data', 'Exportar Datos Clientes'), ('reports.export_pdf', 'Exportar Reportes PDF'), ('campaigns.whatsapp_manual', 'Campañas WhatsApp (Manual)'), ('campaigns.pabbly', 'Webhook Pabbly Connect'), ('appointments.online_booking', 'Reservas Online'), ('gamification.referrals', 'Programa de Referidos')], max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('enabled_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='core.organization')),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'unique_together': {('organization', 'feature_key')},
            },
        ),
        migrations.CreateModel(
            name='UsageLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_type', models.CharField(choices=[('customers', 'Número de Clientes (Máximo)'), ('staff', 'Número de Trabajadores (Máximo)'), ('appointments_monthly', 'Citas por Mes'), ('campaigns_monthly', 'Campañas por Mes'), ('sms_monthly', 'SMS/WhatsApp por Mes'), ('storage_mb', 'Almacenamiento (MB)')], max_length=50)),
                ('limit_value', models.IntegerField(help_text='Usar -1 para ilimitado')),
                ('current_usage', models.IntegerField(default=0)),
                ('enforce_limit', models.BooleanField(default=True, verbose_name='Forzar Límite')),
                ('warning_threshold', models.IntegerField(default=80, help_text='Porcentaje para alerta (0-100)')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_limits', to='core.organization')),
            ],
            options={
                'verbose_name': 'Límite de Uso',
                'verbose_name_plural': 'Límites de Uso',
                'unique_together': {('organization', 'limit_type')},
            },
        ),
    ]
