# Generated by Django 6.0.2 on 2026-02-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_featureflag_usagelimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='stamp_lock_hours',
            field=models.PositiveIntegerField(default=2, verbose_name='Horas de bloqueo entre sellos'),
        ),
    ]
