# Generated by Django 6.0.2 on 2026-02-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_stamp_lock_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='double_stamp_fri',
            field=models.BooleanField(default=False, verbose_name='Viernes Sello Doble'),
        ),
        migrations.AddField(
            model_name='organization',
            name='double_stamp_mon',
            field=models.BooleanField(default=False, verbose_name='Lunes Sello Doble'),
        ),
        migrations.AddField(
            model_name='organization',
            name='double_stamp_sat',
            field=models.BooleanField(default=False, verbose_name='Sábado Sello Doble'),
        ),
        migrations.AddField(
            model_name='organization',
            name='double_stamp_sun',
            field=models.BooleanField(default=False, verbose_name='Domingo Sello Doble'),
        ),
        migrations.AddField(
            model_name='organization',
            name='double_stamp_thu',
            field=models.BooleanField(default=False, verbose_name='Jueves Sello Doble'),
        ),
        migrations.AddField(
            model_name='organization',
            name='double_stamp_tue',
            field=models.BooleanField(default=False, verbose_name='Martes Sello Doble'),
        ),
        migrations.AddField(
            model_name='organization',
            name='double_stamp_wed',
            field=models.BooleanField(default=False, verbose_name='Miércoles Sello Doble'),
        ),
        migrations.AddField(
            model_name='organization',
            name='stamps_expiration_months',
            field=models.PositiveIntegerField(default=0, verbose_name='Meses de vigencia de tarjetas (0 = sin límite)'),
        ),
    ]
