# Generated by Django 6.0.2 on 2026-02-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organization_double_stamp_fri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='feature_key',
            field=models.CharField(choices=[('customers', 'Gestión de Clientes'), ('services', 'Catálogo de Servicios'), ('points', 'Sistema de Puntos'), ('stamps', 'Sistema de Sellos (Punch Cards)'), ('rewards', 'Recompensas'), ('appointments', 'Sistema de Citas'), ('campaigns', 'Campañas de Marketing'), ('reports', 'Reportes Avanzados'), ('subscriptions', 'Suscripciones'), ('integrations', 'Integraciones (Pabbly/Webhooks)'), ('gamification', 'Gamificación'), ('audit', 'Auditoría y Logs'), ('customers.import_csv', 'Importar Clientes CSV'), ('customers.export_data', 'Exportar Datos Clientes'), ('reports.export_pdf', 'Exportar Reportes PDF'), ('campaigns.whatsapp_manual', 'Campañas WhatsApp (Manual)'), ('campaigns.auto_notifications', 'Notificaciones Automáticas (Engagement)'), ('campaigns.pabbly', 'Webhook Pabbly Connect'), ('appointments.online_booking', 'Reservas Online'), ('gamification.referrals', 'Programa de Referidos')], max_length=100),
        ),
    ]
