# Generated by Django 6.0.1 on 2026-02-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_featureflag_feature_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='closing_time',
            field=models.TimeField(default='21:00:00', verbose_name='Hora de Cierre'),
        ),
        migrations.AddField(
            model_name='organization',
            name='opening_time',
            field=models.TimeField(default='09:00:00', verbose_name='Hora de Apertura'),
        ),
    ]
