# Generated by Django 6.0.1 on 2026-02-11 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organization_closing_time_organization_opening_time'),
        ('superadmin', '0002_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='superadmin.plan', verbose_name='Plan de Suscripción'),
        ),
    ]
