# Generated by Django 6.0.1 on 2026-02-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_organization_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='stamp_lock_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Minutos de espera (Cooldown)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='stamp_lock_hours',
            field=models.PositiveIntegerField(default=2, verbose_name='Horas de espera (Cooldown)'),
        ),
    ]
