# Generated by Django 6.0.1 on 2026-02-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_organization_stamp_lock_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='custom_background_color',
            field=models.CharField(default='#f8fafc', max_length=7, verbose_name='Color de Fondo'),
        ),
        migrations.AddField(
            model_name='organization',
            name='custom_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Imagen de Fondo'),
        ),
    ]
