# Generated by Django 6.0.2 on 2026-02-09 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_featureflag_usagelimit'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StampPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la Promoción')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('total_stamps_needed', models.PositiveIntegerField(default=10, verbose_name='Sellos necesarios')),
                ('reward_description', models.CharField(max_length=200, verbose_name='Recompensa (Ej: Corte Gratis)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Promoción de Sellos',
                'verbose_name_plural': 'Promociones de Sellos',
            },
        ),
        migrations.CreateModel(
            name='StampCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stamps', models.PositiveIntegerField(default=0, verbose_name='Sellos actuales')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('is_redeemed', models.BooleanField(default=False, verbose_name='Canjeada')),
                ('last_stamp_at', models.DateTimeField(auto_now=True, verbose_name='Último sello')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_cards', to='customers.customer', verbose_name='Cliente')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='Organización')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='stamps.stamppromotion', verbose_name='Promoción')),
            ],
            options={
                'verbose_name': 'Tarjeta de Sellos',
                'verbose_name_plural': 'Tarjetas de Sellos',
                'unique_together': {('customer', 'promotion', 'is_redeemed')},
            },
        ),
        migrations.CreateModel(
            name='StampTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADD', 'Sello Agregado'), ('REDEEM', 'Recompensa Canjeada'), ('RESET', 'Reinicio / Manual')], default='ADD', max_length=10)),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stamps.stampcard', verbose_name='Tarjeta')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='Organización')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Transacción de Sello',
                'verbose_name_plural': 'Transacciones de Sellos',
            },
        ),
    ]
