# Generated by Django 6.0.2 on 2026-02-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stampcard',
            name='redemption_requested',
            field=models.BooleanField(default=False, verbose_name='Canje solicitado'),
        ),
        migrations.AddField(
            model_name='stampcard',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de solicitud'),
        ),
    ]
