# Generated by Django 6.0.2 on 2026-02-10 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0002_stampcard_redemption_requested_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stampcard',
            unique_together=set(),
        ),
    ]
