# Generated by Django 6.0.2 on 2026-02-10 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
        ('stamps', '0003_alter_stampcard_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamppromotion',
            name='primary_color',
            field=models.CharField(default='#0d6efd', max_length=20, verbose_name='Color de la Tarjeta'),
        ),
        migrations.AddField(
            model_name='stamppromotion',
            name='reward',
            field=models.ForeignKey(blank=True, help_text='Vincular con un premio del catálogo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rewards.reward', verbose_name='Premio vinculado'),
        ),
        migrations.AlterField(
            model_name='stamppromotion',
            name='reward_description',
            field=models.CharField(help_text='Se usa si no hay premio vinculado', max_length=200, verbose_name='Descripción de Recompensa (Fallback)'),
        ),
    ]
