# Generated by Django 6.0.2 on 2026-02-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0004_stamppromotion_primary_color_stamppromotion_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stampcard',
            name='completed_notified',
            field=models.BooleanField(default=False, verbose_name="Notificación 'Completada' enviada"),
        ),
        migrations.AddField(
            model_name='stampcard',
            name='expiring_notified',
            field=models.BooleanField(default=False, verbose_name="Notificación 'Por Vencer' enviada"),
        ),
        migrations.AddField(
            model_name='stampcard',
            name='one_stamp_reminder_sent',
            field=models.BooleanField(default=False, verbose_name="Recordatorio 'Falta 1' enviado"),
        ),
    ]
