# Generated by Django 6.0.1 on 2026-02-10 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organization_closing_time_organization_opening_time'),
        ('customers', '0003_tag_customer_tags'),
        ('stamps', '0005_stampcard_completed_notified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StampRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10, verbose_name='Estado')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Solicitud')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Resolución')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_requests', to='customers.customer', verbose_name='Cliente')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='Organización')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stamps.stamppromotion', verbose_name='Promoción')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
            ],
            options={
                'verbose_name': 'Solicitud de Sello',
                'verbose_name_plural': 'Solicitudes de Sellos',
                'ordering': ['-requested_at'],
            },
        ),
    ]
