# Generated by Django 6.0.2 on 2026-02-09 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_featureflag_usagelimit'),
        ('customers', '0001_initial'),
        ('loyalty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Premio')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('points_cost', models.PositiveIntegerField(verbose_name='Costo en Puntos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válido hasta')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
                'ordering': ['points_cost'],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.PositiveIntegerField(verbose_name='Puntos Gastados')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='Canjeado el')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='customers.customer', verbose_name='Cliente')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='Organización')),
                ('point_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redemption_detail', to='loyalty.pointtransaction', verbose_name='Transacción de Puntos')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Procesado por')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rewards.reward', verbose_name='Premio')),
            ],
            options={
                'verbose_name': 'Canje de Recompensa',
                'verbose_name_plural': 'Canjes de Recompensas',
            },
        ),
    ]
