# Generated by Django 6.0.1 on 2026-02-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido del Mensaje')),
                ('style', models.CharField(choices=[('primary', 'Información (Azul)'), ('warning', 'Aviso (Naranja)'), ('danger', 'Crítico (Rojo)'), ('success', 'Novedad (Verde)'), ('dark', 'Mantenimiento (Negro)')], default='primary', max_length=20, verbose_name='Estilo')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Publicado?')),
                ('show_to_owners', models.BooleanField(default=True, verbose_name='Mostrar a Dueños')),
                ('show_to_staff', models.BooleanField(default=True, verbose_name='Mostrar a Trabajadores')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Dejar vacío para permanente', null=True, verbose_name='Expira el')),
            ],
            options={
                'verbose_name': 'Comunicado Global',
                'verbose_name_plural': 'Comunicados Globales',
                'ordering': ['-created_at'],
            },
        ),
    ]
