# Generated by Django 6.0.1 on 2026-02-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Mensual')),
                ('max_customers', models.IntegerField(default=100, verbose_name='Máximo Clientes')),
                ('max_staff', models.IntegerField(default=5, verbose_name='Máximo Staff')),
                ('max_appointments_monthly', models.IntegerField(default=-1, verbose_name='Citas/Mes (-1 = ilimitado)')),
                ('max_campaigns_monthly', models.IntegerField(default=2, verbose_name='Campañas/Mes')),
                ('enable_whatsapp', models.BooleanField(default=False, verbose_name='WhatsApp Marketing')),
                ('enable_reports', models.BooleanField(default=False, verbose_name='Reportes Avanzados')),
                ('enable_audit', models.BooleanField(default=False, verbose_name='Auditoría y Logs')),
                ('enable_stamps', models.BooleanField(default=True, verbose_name='Punch Cards (Sellos)')),
                ('enable_points', models.BooleanField(default=True, verbose_name='Sistema de Puntos')),
                ('enable_appointments', models.BooleanField(default=False, verbose_name='Sistema de Citas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['price'],
            },
        ),
    ]
