# Generated by Django 6.0.1 on 2026-02-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Si se marca, se asignará a nuevos negocios sin plan.', verbose_name='Plan por Defecto'),
        ),
    ]
