# Generated by Django 6.0.1 on 2026-02-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_plan_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='enable_appointments_online_booking',
            field=models.BooleanField(default=False, verbose_name='Reservas Online'),
        ),
        migrations.AddField(
            model_name='plan',
            name='enable_campaigns_auto_notifications',
            field=models.BooleanField(default=False, verbose_name='Notificaciones Automáticas (Engagement)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='enable_campaigns_pabbly',
            field=models.BooleanField(default=False, verbose_name='Webhook Pabbly Connect'),
        ),
        migrations.AddField(
            model_name='plan',
            name='enable_campaigns_whatsapp_manual',
            field=models.BooleanField(default=False, verbose_name='Campañas WhatsApp (Manual)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='enable_customers',
            field=models.BooleanField(default=True, verbose_name='Gestión de Clientes'),
        ),
        migrations.AddField(
            model_name='plan',
            name='enable_customers_export_data',
            field=models.BooleanField(default=False, verbose_name='Exportar Datos Clientes'),
        ),
        migrations.AddField(
            model_name='plan',
            name='enable_customers_import_csv',
            field=models.BooleanField(default=False, verbose_name='Importar Clientes CSV'),
        ),
        migrations.AddField(
            model_name='plan',
            name='enable_gamification',
            field=models.BooleanField(default=False, verbose_name='Gamificación'),
        ),
        migrations.AddField(
            model_name='plan',
            name='enable_gamification_referrals',
            field=models.BooleanField(default=False, verbose_name='Programa de Referidos'),
        ),
        migrations.AddField(
            model_name='plan',
            name='enable_integrations',
            field=models.BooleanField(default=False, verbose_name='Integraciones (Pabbly/Webhooks)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='enable_reports_export_pdf',
            field=models.BooleanField(default=False, verbose_name='Exportar Reportes PDF'),
        ),
        migrations.AddField(
            model_name='plan',
            name='enable_rewards',
            field=models.BooleanField(default=True, verbose_name='Recompensas'),
        ),
        migrations.AddField(
            model_name='plan',
            name='enable_services',
            field=models.BooleanField(default=True, verbose_name='Catálogo de Servicios'),
        ),
        migrations.AddField(
            model_name='plan',
            name='enable_subscriptions',
            field=models.BooleanField(default=False, verbose_name='Suscripciones'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='enable_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Campañas de Marketing'),
        ),
    ]
