# Generated by Django 6.0.1 on 2026-02-10 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_featureflag_feature_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de Sesión'), ('STAMP_ADD', 'Sello Agregado'), ('STAMP_REDEEM', 'Sello Canjeado'), ('POINTS_ADD', 'Puntos Agregados'), ('POINTS_REDEEM', 'Puntos Canjeados')], max_length=20, verbose_name='Acción')),
                ('resource', models.CharField(max_length=100, verbose_name='Recurso (Ej: Cliente, Sello)')),
                ('description', models.TextField(verbose_name='Descripción del cambio')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization', verbose_name='Organización')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-created_at'],
            },
        ),
    ]
