# Generated by Django 6.0.1 on 2026-02-10 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('customers', '0003_tag_customer_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='customers.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de Sesión'), ('STAMP_ADD', 'Sello Agregado'), ('STAMP_REDEEM', 'Sello Canjeado'), ('POINTS_ADD', 'Puntos Agregados'), ('POINTS_REDEEM', 'Puntos Canjeados'), ('WA_SENT', 'WhatsApp Enviado')], max_length=20, verbose_name='Acción'),
        ),
    ]
